-- Global food catalog and example recipes (user_id = null → readable by every user).
-- Shipped as a migration (not only seed.sql) so production users start with a usable catalog.
-- Nutrients per 100 g / 100 ml of the raw / uncooked product.

insert into public.food_items
  (name, category, base_amount, base_unit, calories, protein, carbs, fat, fiber, grams_per_piece)
values
  ('Hähnchenbrust',             'protein',    100, 'g',  110, 23.0,  0.0,  1.5, 0.0,  null),
  ('Putenbrust',                'protein',    100, 'g',  105, 24.0,  0.0,  1.0, 0.0,  null),
  ('Rinderhack (5 % Fett)',     'protein',    100, 'g',  129, 21.0,  0.0,  5.0, 0.0,  null),
  ('Eier',                      'protein',    100, 'g',  143, 12.6,  0.7,  9.5, 0.0,  60),
  ('Skyr natur',                'dairy',      100, 'g',   63, 11.0,  4.0,  0.2, 0.0,  null),
  ('Magerquark',                'dairy',      100, 'g',   67, 12.0,  4.0,  0.3, 0.0,  null),
  ('Milch 1,5 %',               'dairy',      100, 'ml',  47,  3.4,  4.9,  1.5, 0.0,  null),
  ('Whey Protein Vanille',      'protein',    100, 'g',  380, 78.0,  7.0,  5.0, 0.0,  null),
  ('Basmatireis',               'carbs',      100, 'g',  350,  8.0, 77.0,  0.6, 1.3,  null),
  ('Pasta (Hartweizen)',        'carbs',      100, 'g',  355, 12.5, 71.0,  1.5, 3.0,  null),
  ('Kartoffeln',                'carbs',      100, 'g',   77,  2.0, 17.0,  0.1, 2.2,  null),
  ('Haferflocken',              'carbs',      100, 'g',  372, 13.5, 58.7,  7.0, 10.0, null),
  ('Weizen-Tortilla',           'carbs',      100, 'g',  310,  8.5, 51.0,  7.5, 3.0,  62),
  ('Kidneybohnen (abgetropft)', 'carbs',      100, 'g',   98,  7.0, 13.0,  0.6, 7.0,  null),
  ('Brokkoli',                  'vegetables', 100, 'g',   35,  3.0,  2.7,  0.4, 3.0,  null),
  ('Paprika rot',               'vegetables', 100, 'g',   31,  1.0,  6.0,  0.3, 2.1,  null),
  ('Zwiebeln',                  'vegetables', 100, 'g',   40,  1.1,  7.6,  0.1, 1.7,  null),
  ('Knoblauch',                 'vegetables', 100, 'g',  149,  6.4, 30.0,  0.5, 2.1,  4),
  ('Erbsen (TK)',               'vegetables', 100, 'g',   81,  5.4,  9.0,  0.4, 5.0,  null),
  ('Mais (abgetropft)',         'vegetables', 100, 'g',   81,  2.9, 14.0,  1.2, 2.7,  null),
  ('Gehackte Tomaten (Dose)',   'vegetables', 100, 'g',   24,  1.2,  3.5,  0.2, 1.0,  null),
  ('Eisbergsalat',              'vegetables', 100, 'g',   14,  0.9,  1.8,  0.1, 1.2,  null),
  ('Beerenmischung (TK)',       'fruit',      100, 'g',   45,  1.0,  8.0,  0.4, 4.0,  null),
  ('Banane',                    'fruit',      100, 'g',   89,  1.1, 20.0,  0.3, 2.6,  120),
  ('Olivenöl',                  'fats',       100, 'g',  884,  0.0,  0.0, 100.0, 0.0, null),
  ('Chiasamen',                 'fats',       100, 'g',  486, 17.0,  7.7, 31.0, 34.0, null),
  ('Kokosmilch light',          'sauces',     100, 'ml',  70,  0.7,  2.5,  6.5, 0.0,  null),
  ('Sojasauce',                 'sauces',     100, 'ml',  53,  8.0,  4.9,  0.6, 0.0,  null),
  ('Honig',                     'other',      100, 'g',  304,  0.3, 82.0,  0.0, 0.0,  null),
  ('Currypulver',               'spices',     100, 'g',  325, 14.0, 25.0, 14.0, 33.0, null),
  ('Chilipulver',               'spices',     100, 'g',  282, 13.0, 25.0, 14.0, 35.0, null);

insert into public.recipes
  (name, description, category, tags, servings, prep_time, cook_time,
   fridge_life_days, freezer_life_days, storage_notes, instructions)
values
  ('Chicken Rice Bowl', 'Der Meal-Prep-Klassiker: Hähnchen, Reis und Gemüse.', 'lunch',
   '{meal_prep,high_protein}', 4, 15, 25, 4, 30,
   'Luftdicht in Boxen im Kühlschrank lagern, vor dem Essen gut erhitzen.',
   array['Ofen auf 200 °C vorheizen.', 'Reis nach Packungsanleitung kochen.',
         'Hähnchen würfeln, mit Öl und Sojasauce marinieren.',
         'Hähnchen 20 Minuten im Ofen garen.', 'Brokkoli und Paprika dämpfen.',
         'Alles auf 4 Boxen verteilen.']),
  ('Beef Chili', 'Würziges Chili con Carne – perfekt zum Einfrieren.', 'dinner',
   '{meal_prep,high_protein}', 4, 15, 40, 4, 90,
   'Portionsweise einfrieren, im Kühlschrank auftauen lassen.',
   array['Zwiebeln, Knoblauch und Paprika schneiden.', 'Rinderhack in Öl scharf anbraten.',
         'Gemüse und Chilipulver zugeben, kurz mitrösten.',
         'Tomaten, Bohnen und Mais zugeben, 30 Minuten köcheln lassen.',
         'Abschmecken und in Boxen abfüllen.']),
  ('Protein Oats', 'Cremiger Porridge mit Whey und Beeren.', 'breakfast',
   '{high_protein,quick}', 1, 2, 5, 2, null, null,
   array['Haferflocken mit Milch aufkochen.', 'Vom Herd nehmen und Whey einrühren.',
         'Mit Beeren toppen.']),
  ('High Protein Pasta', 'Bolognese mit Magerquark für extra Protein.', 'dinner',
   '{meal_prep,high_protein}', 4, 10, 25, 4, 60, null,
   array['Pasta nach Packungsanleitung kochen.', 'Zwiebeln und Knoblauch hacken.',
         'Rinderhack in Öl anbraten, Zwiebeln und Knoblauch zugeben.',
         'Tomaten zugeben und 15 Minuten köcheln lassen.',
         'Vom Herd nehmen, Magerquark einrühren, mit Pasta mischen und portionieren.']),
  ('Burrito Bowl', 'Mexikanische Bowl mit Hähnchen, Bohnen und Mais.', 'lunch',
   '{meal_prep,high_protein}', 4, 15, 25, 4, 30, null,
   array['Reis kochen.', 'Hähnchen würfeln und mit Chilipulver würzen.',
         'Hähnchen mit Zwiebeln und Paprika in Öl anbraten.',
         'Bohnen und Mais erwärmen.', 'Alles auf 4 Boxen verteilen.']),
  ('Overnight Oats', 'Ohne Kochen: am Vorabend vorbereitet.', 'breakfast',
   '{meal_prep}', 2, 10, 0, 3, null, 'Im Glas mit Deckel im Kühlschrank lagern.',
   array['Haferflocken, Chiasamen, Skyr und Milch verrühren.', 'Honig unterrühren.',
         'In 2 Gläser füllen und Beeren darauf geben.', 'Über Nacht kalt stellen.']),
  ('Chicken Curry', 'Mildes Curry mit Kokosmilch und Erbsen.', 'dinner',
   '{meal_prep,high_protein}', 4, 15, 25, 4, 60, null,
   array['Reis kochen.', 'Zwiebeln und Knoblauch hacken, Hähnchen würfeln.',
         'Hähnchen anbraten, Zwiebeln, Knoblauch und Currypulver zugeben.',
         'Mit Kokosmilch ablöschen, Erbsen zugeben und 15 Minuten köcheln lassen.',
         'Mit Reis portionieren.']),
  ('Egg Fried Rice', 'Gebratener Reis mit Ei, Hähnchen und Gemüse.', 'lunch',
   '{meal_prep,quick}', 3, 10, 15, 3, 30, 'Reis vor dem Erhitzen mit etwas Wasser beträufeln.',
   array['Reis kochen und abkühlen lassen (ideal: vom Vortag).',
         'Hähnchen würfeln und in Öl anbraten.', 'Zwiebeln, Paprika und Erbsen zugeben.',
         'Eier in die Pfanne schlagen und stocken lassen.',
         'Reis und Sojasauce zugeben, alles kräftig durchbraten.']),
  ('Turkey Wrap', 'Schnelle Wraps mit Putenbrust und Skyr-Dip.', 'lunch',
   '{quick,high_protein}', 2, 10, 10, 2, null, 'Sauce getrennt lagern, damit der Wrap nicht durchweicht.',
   array['Putenbrust in Streifen schneiden und anbraten.', 'Salat und Paprika schneiden.',
         'Tortillas mit Skyr bestreichen, mit Pute und Gemüse belegen und einrollen.']),
  ('Skyr Berry Bowl', 'Proteinreicher Snack in 3 Minuten.', 'snack',
   '{quick,high_protein}', 1, 3, 0, 1, null, null,
   array['Skyr in eine Schale geben.', 'Beeren und Haferflocken darauf verteilen.',
         'Mit Honig beträufeln.']);

insert into public.recipe_ingredients (recipe_id, food_item_id, amount, unit, sort_order)
select r.id, f.id, v.amount, v.unit::public.food_unit, v.sort_order
from (values
  ('Chicken Rice Bowl', 'Hähnchenbrust', 600, 'g', 1),
  ('Chicken Rice Bowl', 'Basmatireis', 280, 'g', 2),
  ('Chicken Rice Bowl', 'Brokkoli', 400, 'g', 3),
  ('Chicken Rice Bowl', 'Paprika rot', 200, 'g', 4),
  ('Chicken Rice Bowl', 'Olivenöl', 15, 'g', 5),
  ('Chicken Rice Bowl', 'Sojasauce', 30, 'ml', 6),
  ('Beef Chili', 'Rinderhack (5 % Fett)', 500, 'g', 1),
  ('Beef Chili', 'Kidneybohnen (abgetropft)', 250, 'g', 2),
  ('Beef Chili', 'Gehackte Tomaten (Dose)', 800, 'g', 3),
  ('Beef Chili', 'Mais (abgetropft)', 140, 'g', 4),
  ('Beef Chili', 'Zwiebeln', 150, 'g', 5),
  ('Beef Chili', 'Paprika rot', 200, 'g', 6),
  ('Beef Chili', 'Knoblauch', 2, 'piece', 7),
  ('Beef Chili', 'Chilipulver', 10, 'g', 8),
  ('Beef Chili', 'Olivenöl', 10, 'g', 9),
  ('Protein Oats', 'Haferflocken', 80, 'g', 1),
  ('Protein Oats', 'Milch 1,5 %', 250, 'ml', 2),
  ('Protein Oats', 'Whey Protein Vanille', 30, 'g', 3),
  ('Protein Oats', 'Beerenmischung (TK)', 100, 'g', 4),
  ('High Protein Pasta', 'Pasta (Hartweizen)', 320, 'g', 1),
  ('High Protein Pasta', 'Rinderhack (5 % Fett)', 400, 'g', 2),
  ('High Protein Pasta', 'Gehackte Tomaten (Dose)', 800, 'g', 3),
  ('High Protein Pasta', 'Zwiebeln', 100, 'g', 4),
  ('High Protein Pasta', 'Knoblauch', 2, 'piece', 5),
  ('High Protein Pasta', 'Magerquark', 250, 'g', 6),
  ('High Protein Pasta', 'Olivenöl', 10, 'g', 7),
  ('Burrito Bowl', 'Hähnchenbrust', 500, 'g', 1),
  ('Burrito Bowl', 'Basmatireis', 240, 'g', 2),
  ('Burrito Bowl', 'Kidneybohnen (abgetropft)', 250, 'g', 3),
  ('Burrito Bowl', 'Mais (abgetropft)', 140, 'g', 4),
  ('Burrito Bowl', 'Paprika rot', 200, 'g', 5),
  ('Burrito Bowl', 'Zwiebeln', 100, 'g', 6),
  ('Burrito Bowl', 'Chilipulver', 8, 'g', 7),
  ('Burrito Bowl', 'Olivenöl', 10, 'g', 8),
  ('Overnight Oats', 'Haferflocken', 120, 'g', 1),
  ('Overnight Oats', 'Skyr natur', 300, 'g', 2),
  ('Overnight Oats', 'Milch 1,5 %', 200, 'ml', 3),
  ('Overnight Oats', 'Chiasamen', 20, 'g', 4),
  ('Overnight Oats', 'Beerenmischung (TK)', 150, 'g', 5),
  ('Overnight Oats', 'Honig', 10, 'g', 6),
  ('Chicken Curry', 'Hähnchenbrust', 600, 'g', 1),
  ('Chicken Curry', 'Kokosmilch light', 400, 'ml', 2),
  ('Chicken Curry', 'Currypulver', 15, 'g', 3),
  ('Chicken Curry', 'Zwiebeln', 150, 'g', 4),
  ('Chicken Curry', 'Erbsen (TK)', 200, 'g', 5),
  ('Chicken Curry', 'Basmatireis', 280, 'g', 6),
  ('Chicken Curry', 'Knoblauch', 2, 'piece', 7),
  ('Egg Fried Rice', 'Basmatireis', 210, 'g', 1),
  ('Egg Fried Rice', 'Eier', 4, 'piece', 2),
  ('Egg Fried Rice', 'Hähnchenbrust', 300, 'g', 3),
  ('Egg Fried Rice', 'Erbsen (TK)', 200, 'g', 4),
  ('Egg Fried Rice', 'Paprika rot', 150, 'g', 5),
  ('Egg Fried Rice', 'Zwiebeln', 100, 'g', 6),
  ('Egg Fried Rice', 'Sojasauce', 40, 'ml', 7),
  ('Egg Fried Rice', 'Olivenöl', 15, 'g', 8),
  ('Turkey Wrap', 'Weizen-Tortilla', 2, 'piece', 1),
  ('Turkey Wrap', 'Putenbrust', 250, 'g', 2),
  ('Turkey Wrap', 'Eisbergsalat', 60, 'g', 3),
  ('Turkey Wrap', 'Paprika rot', 100, 'g', 4),
  ('Turkey Wrap', 'Skyr natur', 100, 'g', 5),
  ('Skyr Berry Bowl', 'Skyr natur', 300, 'g', 1),
  ('Skyr Berry Bowl', 'Beerenmischung (TK)', 150, 'g', 2),
  ('Skyr Berry Bowl', 'Haferflocken', 30, 'g', 3),
  ('Skyr Berry Bowl', 'Honig', 10, 'g', 4)
) as v (recipe, food, amount, unit, sort_order)
join public.recipes r on r.name = v.recipe and r.user_id is null
join public.food_items f on f.name = v.food and f.user_id is null;
